complete_project/copied_project/sample_project/config/routes.rb
Rails.application.routes.draw do

  if Rails.env.development? #application running(env)
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  
  
  # resources :products, except:[:show]
  #resources :products, only: [:edit, :destroy]

  # resources :products, only: [:show] do
  #    collection do     
  #      get 'out-of-stock' 
  #        end
  #       end

 resources :products
  resources :customers
  resources :orders

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  #Assignment (27/1/26)
  # resources :products,skip:[show]  ---> this is Rails will generate all RESTful routes for products EXCEPT the show route.
  
end

complete_project/copied_project/sample_project/app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
end

complete_project/copied_project/sample_project/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    def index
    @orders = Order.all
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    if @order.save
      redirect_to orders_path, notice: "Order created successfully"
    else
      render :new
    end
  end

  private

  def order_params
    params.require(:order).permit(:details, :count)
  end
end

complete_project/copied_project/sample_project/app/helpers/orders_helper.rb
module OrdersHelper
end

complete_project/copied_project/sample_project/app/views/orders/index.html.erb
<h2>Orders List</h2>

<table border="1">
  <tr>
    <th>Details</th>
    <th>Count</th>
  </tr>

  <% @orders.each do |order| %>
    <tr>
      <td><%= order.details %></td>
      <td><%= order.count %></td>
    </tr>
  <% end %>
</table>

<%= link_to "New Order", new_order_path %>

complete_project/copied_project/sample_project/app/views/orders/new.html.erb
<h2>New Order</h2>

<%= form_with model: @order do |f| %>
  <div>
    <%= f.label :details %><br>
    <%= f.text_field :details %>
  </div>

  <div>
    <%= f.label :count %><br>
    <%= f.number_field :count %>
  </div>

  <div>
    <%= f.submit "Create Order" %>
  </div>
<% end %>