day_app/config/routes.rb
Rails.application.routes.draw do
  resources :product1s
  resources :products
  resources :customers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

day_app/app/models/customer.rb
class Customer < ApplicationRecord
end

day_app/app/models/product.rb
class Product < ApplicationRecord
end

day_app/app/models/product1.rb
class Product1 < ApplicationRecord
end

day_app/app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: %i[ show edit update destroy ]

  # GET /customers or /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1 or /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers or /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: "Customer was successfully created." }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1 or /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: "Customer was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1 or /customers/1.json
  def destroy
    @customer.destroy!

    respond_to do |format|
      format.html { redirect_to customers_path, notice: "Customer was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.expect(customer: [ :name, :email ])
    end
end

day_app/app/controllers/product1s_controller.rb
class Product1sController < ApplicationController
  before_action :set_product1, only: %i[ show edit update destroy ]

  # GET /product1s or /product1s.json
  def index
    @product1s = Product1.all
  end

  # GET /product1s/1 or /product1s/1.json
  def show
  end

  # GET /product1s/new
  def new
    @product1 = Product1.new
  end

  # GET /product1s/1/edit
  def edit
  end

  # POST /product1s or /product1s.json
  def create
    @product1 = Product1.new(product1_params)

    respond_to do |format|
      if @product1.save
        format.html { redirect_to @product1, notice: "Product1 was successfully created." }
        format.json { render :show, status: :created, location: @product1 }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product1.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product1s/1 or /product1s/1.json
  def update
    respond_to do |format|
      if @product1.update(product1_params)
        format.html { redirect_to @product1, notice: "Product1 was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @product1 }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product1.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product1s/1 or /product1s/1.json
  def destroy
    @product1.destroy!

    respond_to do |format|
      format.html { redirect_to product1s_path, notice: "Product1 was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product1
      @product1 = Product1.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def product1_params
      params.expect(product1: [ :name, :description, :price, :stock, :stock ])
    end
end

day_app/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy!

    respond_to do |format|
      format.html { redirect_to products_path, notice: "Product was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.expect(product: [ :name, :description, :price, :stock, :stock ])
    end
end

day_app/app/helpers/product1s_helper.rb
module Product1sHelper
end

day_app/app/views/customers/_customer.html.erb
<div id="<%= dom_id customer %>">
  <div>
    <strong>Name:</strong>
    <%= customer.name %>
  </div>

  <div>
    <strong>Email:</strong>
    <%= customer.email %>
  </div>

</div>

day_app/app/views/customers/_form.html.erb
<%= form_with(model: customer) do |form| %>
  <% if customer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
        <% customer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

day_app/app/views/customers/edit.html.erb
<% content_for :title, "Editing customer" %>

<h1>Editing customer</h1>

<%= render "form", customer: @customer %>

<br>

<div>
  <%= link_to "Show this customer", @customer %> |
  <%= link_to "Back to customers", customers_path %>
</div>

day_app/app/views/customers/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Customers" %>

<h1>Customers</h1>

<div id="customers">
  <% @customers.each do |customer| %>
    <%= render customer %>
    <p>
      <%= link_to "Show this customer", customer %>
    </p>
  <% end %>
</div>

<%= link_to "New customer", new_customer_path %>

day_app/app/views/customers/new.html.erb
<% content_for :title, "New customer" %>

<h1>New customer</h1>

<%= render "form", customer: @customer %>

<br>

<div>
  <%= link_to "Back to customers", customers_path %>
</div>

day_app/app/views/customers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @customer %>

<div>
  <%= link_to "Edit this customer", edit_customer_path(@customer) %> |
  <%= link_to "Back to customers", customers_path %>

  <%= button_to "Destroy this customer", @customer, method: :delete %>
</div>

day_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Day App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Day App">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

day_app/app/views/product1s/_form.html.erb
<%= form_with(model: product1) do |form| %>
  <% if product1.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product1.errors.count, "error") %> prohibited this product1 from being saved:</h2>

      <ul>
        <% product1.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.textarea :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :stock, style: "display: block" %>
    <%= form.text_field :stock %>
  </div>

  <div>
    <%= form.label :stock, style: "display: block" %>
    <%= form.number_field :stock %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

day_app/app/views/product1s/_product1.html.erb
<div id="<%= dom_id product1 %>">
  <div>
    <strong>Name:</strong>
    <%= product1.name %>
  </div>

  <div>
    <strong>Description:</strong>
    <%= product1.description %>
  </div>

  <div>
    <strong>Price:</strong>
    <%= product1.price %>
  </div>

  <div>
    <strong>Stock:</strong>
    <%= product1.stock %>
  </div>

  <div>
    <strong>Stock:</strong>
    <%= product1.stock %>
  </div>

</div>

day_app/app/views/product1s/edit.html.erb
<% content_for :title, "Editing product1" %>

<h1>Editing product1</h1>

<%= render "form", product1: @product1 %>

<br>

<div>
  <%= link_to "Show this product1", @product1 %> |
  <%= link_to "Back to product1s", product1s_path %>
</div>

day_app/app/views/product1s/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Product1s" %>

<h1>Product1s</h1>

<div id="product1s">
  <% @product1s.each do |product1| %>
    <%= render product1 %>
    <p>
      <%= link_to "Show this product1", product1 %>
    </p>
  <% end %>
</div>

<%= link_to "New product1", new_product1_path %>

day_app/app/views/product1s/new.html.erb
<% content_for :title, "New product1" %>

<h1>New product1</h1>

<%= render "form", product1: @product1 %>

<br>

<div>
  <%= link_to "Back to product1s", product1s_path %>
</div>

day_app/app/views/product1s/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product1 %>

<div>
  <%= link_to "Edit this product1", edit_product1_path(@product1) %> |
  <%= link_to "Back to product1s", product1s_path %>

  <%= button_to "Destroy this product1", @product1, method: :delete %>
</div>

day_app/app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.textarea :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :stock, style: "display: block" %>
    <%= form.text_field :stock %>
  </div>

  <div>
    <%= form.label :stock, style: "display: block" %>
    <%= form.number_field :stock %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

day_app/app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <div>
    <strong>Name:</strong>
    <%= product.name %>
  </div>

  <div>
    <strong>Description:</strong>
    <%= product.description %>
  </div>

  <div>
    <strong>Price:</strong>
    <%= product.price %>
  </div>

  <div>
    <strong>Stock:</strong>
    <%= product.stock %>
  </div>

  <div>
    <strong>Stock:</strong>
    <%= product.stock %>
  </div>

</div>

day_app/app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Products" %>

<h1>Products</h1>

<div id="products">
  <% @products.each do |product| %>
    <%= render product %>
    <p>
      <%= link_to "Show this product", product %>
    </p>
  <% end %>
</div>

<%= link_to "New product", new_product_path %>

day_app/app/views/products/new.html.erb
<% content_for :title, "New product" %>

<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

day_app/app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div>